### ISSUE TITLE
Add Initial Transaction domain models to the Quibill.Domain

### ISSUE THREAD

**Issue by tloltman** [tloltman/Qbill-backend#3]
You can follow our design:
https://docs.google.com/drawings/d/1DvGt3_vCgilnX1nmGiMbwz6cgW0TBD_Bp1UOYn4S3WA/edit

**Don't Forget** To create a new branch from develop to work on this issue

**Comment by whimstack** [comment]
@tloltman  If the latest commit looks good then this issue should be complete.
