### ISSUE TITLE
Add initial User for development testing

### ISSUE THREAD

**Issue by tloltman** [tloltman/Qbill-backend#4]
**This requires that [#5](https://github.com/tloltman/Quibill-backend/issues/5) Be finished first**

This can be done either by using the database Seed method which requires us to turn on Code-First migrations (I've never tried this before and it might not be that friendly with source control), or it can be added to the application startup file which I would recommend.

The code will be added to the Quibill.Web/Startup.cs file and here is an example of (pretty much exactly) what to do:
http://www.c-sharpcorner.com/UploadFile/asmabegam/Asp-Net-mvc-5-security-and-creating-user-role/

I also added an admin area to the web app which you can access by going to 'localhost:xxxxx/admin' while your project is running. I made it so you can't access this area unless you are authorized with the "Admin" role. So a good test would be to add the "Admin" role to the user as described in the example above, then run the application, sign in as the user your hard coded, and try to go to the (currently empty and useless) admin area.

**Comment by whimstack** [comment]
Tested and it works.
